export const TAMIL_NADU_DISTRICTS: Record<string, string[]> = {
  "Ariyalur": ["Ariyalur", "Sendurai", "Jayankondam", "T.Palur"],
  "Chengalpattu": ["Chengalpattu", "Cheyyur", "Thiruporur", "Madurantakam", "Tambaram", "Vandalur"],
  "Chennai": ["Chennai North", "Chennai South", "Chennai Central", "Madhavaram", "Sholinganallur"],
  "Coimbatore": ["Coimbatore North", "Coimbatore South", "Annur", "Mettupalayam", "Pollachi", "Sulur", "Valparai"],
  "Cuddalore": ["Cuddalore", "Bhuvanagiri", "Chidambaram", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Vriddhachalam"],
  "Dharmapuri": ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Pappireddipatti"],
  "Dindigul": ["Dindigul", "Attur", "Natham", "Nilakottai", "Oddanchatram", "Palani", "Reddiarchathram", "Vedasandur"],
  "Erode": ["Erode", "Bhavani", "Gobichettipalayam", "Modakurichi", "Nambiyur", "Perundurai", "Sathiyamangalam"],
  "Kallakurichi": ["Kallakurichi", "Chinnasalem", "Sankarapuram", "Tirukoilur", "Ulundurpet"],
  "Kancheepuram": ["Kancheepuram", "Kancheepuram North", "Kancheepuram South", "Sriperumbudur", "Walajabad", "Uthiramerur"],
  "Kanniyakumari": ["Agastheeswaram", "Killiyoor", "Vilavancode", "Kalkulam", "Thovalai"],
  "Karur": ["Karur", "Aravakurichi", "Kadavur", "Krishnarayapuram", "Kulithalai", "Manmangalam"],
  "Krishnagiri": ["Krishnagiri", "Bargur", "Denkanikotai", "Hosur", "Kelamangalam", "Pochampalli", "Uthangarai", "Veppanapalli"],
  "Madurai": ["Madurai North", "Madurai South", "Melur", "Peraiyur", "Thirumangalam", "Usilampatti", "Vadipatti"],
  "Mayiladuthurai": ["Mayiladuthurai", "Kuthalam", "Poompuhar", "Sirkazhi", "Tharangambadi"],
  "Nagapattinam": ["Nagapattinam", "Kilvelur", "Sirkali", "Tharangambadi", "Vedaranyam"],
  "Namakkal": ["Namakkal", "Kolli Hills", "Kumarapalayam", "Mohanur", "Paramathi-Velur", "Rasipuram", "Tiruchengode"],
  "Nilgiris": ["Coonoor", "Gudalur", "Kotagiri", "Ooty", "Panthalur", "Udhagamandalam"],
  "Perambalur": ["Perambalur", "Alathur", "Kunnam", "Veppanthattai"],
  "Pudukottai": ["Pudukottai", "Alangudi", "Aranthangi", "Avudayarkoil", "Gandarvakkottai", "Illupur", "Karambakudi", "Kulathur", "Manamelkudi", "Viralimalai"],
  "Ramanathapuram": ["Ramanathapuram", "Kadaladi", "Mudukulathur", "Paramakudi", "Rajasingamangalam", "Rameswaram", "Tiruvadanai"],
  "Ranipet": ["Arakkonam", "Arcot", "Sholinghur", "Vellore Rural", "Walajah"],
  "Salem": ["Salem", "Attur", "Edappadi", "Gangavalli", "Mettur", "Omalur", "Sankari", "Valapadi", "Yercaud"],
  "Sivaganga": ["Sivaganga", "Devakottai", "Ilayangudi", "Karaikudi", "Manamadurai", "Thiruppuvanam", "Tiruppattur"],
  "Tenkasi": ["Tenkasi", "Alangulam", "Kadayanallur", "Sankarankoil", "Shenkottai", "Sivagiri", "V.K.Pudur"],
  "Thanjavur": ["Thanjavur", "Budalur", "Kumbakonam", "Orathanadu", "Papanasam", "Peravurani", "Pattukottai", "Thiruvaiyaru", "Thiruvidaimarudur"],
  "Theni": ["Theni", "Andipatti", "Bodinayakanur", "Chinnamanur", "Periyakulam", "Uthamapalayam"],
  "Thoothukudi": ["Thoothukudi", "Kovilpatti", "Ottapidaram", "Srivaikuntam", "Thiruchendur", "Vilathikulam"],
  "Tiruchirappalli": ["Tiruchirappalli", "Lalgudi", "Manapparai", "Musiri", "Srirangam", "Thottiam", "Thuraiyur", "Tiruverumbur"],
  "Tirunelveli": ["Tirunelveli", "Ambasamudram", "Cheranmahadevi", "Nanguneri", "Palayamkottai", "Radhapuram", "Tenkasi", "Shencottai"],
  "Tirupathur": ["Tirupathur", "Ambur", "Jolarpet", "Natrampalli", "Vaniyambadi"],
  "Tiruppur": ["Tiruppur", "Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Udumalpet", "Uthukuli"],
  "Tiruvallur": ["Tiruvallur", "Ambattur", "Avadi", "Gummidipoondi", "Minjur", "Ponneri", "Poonamallee", "Tiruttani"],
  "Tiruvannamalai": ["Tiruvannamalai", "Arni", "Chetpet", "Chengam", "Kalasapakkam", "Polur", "Thellar", "Vandavasi", "Vembakkam"],
  "Tiruvarur": ["Tiruvarur", "Kodavasal", "Koradachery", "Mannargudi", "Nannilam", "Needamangalam", "Papanasam", "Thiruthuraipoondi", "Valangaiman"],
  "Vellore": ["Vellore", "Anaicut", "Gudiyatham", "Katpadi", "Pernambut", "Vaniyambadi"],
  "Viluppuram": ["Viluppuram", "Gingee", "Kallakurichi", "Mailam", "Marakkanam", "Mugaiyur", "Sankarapuram", "Tindivanam", "Ulundurpet", "Vikravandi"],
  "Virudhunagar": ["Virudhunagar", "Aruppukkottai", "Kariapatti", "Rajapalayam", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Vembakottai", "Watrap"],
};

export const DISTRICT_RTO_CODES: Record<string, string> = {
  "Ariyalur": "TN61",
  "Chengalpattu": "TN19",
  "Chennai": "TN01",
  "Coimbatore": "TN37",
  "Cuddalore": "TN31",
  "Dharmapuri": "TN29",
  "Dindigul": "TN57",
  "Erode": "TN33",
  "Kallakurichi": "TN15",
  "Kancheepuram": "TN21",
  "Kanniyakumari": "TN74",
  "Karur": "TN47",
  "Krishnagiri": "TN24",
  "Madurai": "TN58",
  "Mayiladuthurai": "TN82",
  "Nagapattinam": "TN51",
  "Namakkal": "TN28",
  "Nilgiris": "TN43",
  "Perambalur": "TN56",
  "Pudukottai": "TN55",
  "Ramanathapuram": "TN65",
  "Ranipet": "TN73",
  "Salem": "TN27",
  "Sivaganga": "TN63",
  "Tenkasi": "TN76",
  "Thanjavur": "TN49",
  "Theni": "TN60",
  "Thoothukudi": "TN69",
  "Tiruchirappalli": "TN45",
  "Tirunelveli": "TN72",
  "Tupathur": "TN83",
  "Tiruppur": "TN39",
  "Tiruvallur": "TN20",
  "Tiruvannamalai": "TN25",
  "Tiruvarur": "TN50",
  "Vellore": "TN23",
  "Viluppuram": "TN32",
  "Virudhunagar": "TN67",
};

export const STATE_CONFIG = {
  "Tamil Nadu": TAMIL_NADU_DISTRICTS
};

